// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: invoice.proto

package com.prakhar.invoice;

public final class InvoiceOuterClass {
  private InvoiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code State}
   */
  public enum State
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NEW = 0;</code>
     */
    NEW(0),
    /**
     * <code>PAID = 1;</code>
     */
    PAID(1),
    /**
     * <code>FAILED = 2;</code>
     */
    FAILED(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NEW = 0;</code>
     */
    public static final int NEW_VALUE = 0;
    /**
     * <code>PAID = 1;</code>
     */
    public static final int PAID_VALUE = 1;
    /**
     * <code>FAILED = 2;</code>
     */
    public static final int FAILED_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static State valueOf(int value) {
      return forNumber(value);
    }

    public static State forNumber(int value) {
      switch (value) {
        case 0: return NEW;
        case 1: return PAID;
        case 2: return FAILED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<State>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        State> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<State>() {
            public State findValueByNumber(int number) {
              return State.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.prakhar.invoice.InvoiceOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final State[] VALUES = values();

    public static State valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private State(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:State)
  }

  public interface InvoiceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Invoice)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>float amount = 2;</code>
     */
    float getAmount();

    /**
     * <code>string customerId = 3;</code>
     */
    java.lang.String getCustomerId();
    /**
     * <code>string customerId = 3;</code>
     */
    com.google.protobuf.ByteString
        getCustomerIdBytes();

    /**
     * <code>.State state = 4;</code>
     */
    int getStateValue();
    /**
     * <code>.State state = 4;</code>
     */
    com.prakhar.invoice.InvoiceOuterClass.State getState();
  }
  /**
   * Protobuf type {@code Invoice}
   */
  public  static final class Invoice extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Invoice)
      InvoiceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Invoice.newBuilder() to construct.
    private Invoice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Invoice() {
      id_ = "";
      amount_ = 0F;
      customerId_ = "";
      state_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Invoice(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 21: {

              amount_ = input.readFloat();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              customerId_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              state_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.prakhar.invoice.InvoiceOuterClass.internal_static_Invoice_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.prakhar.invoice.InvoiceOuterClass.internal_static_Invoice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.prakhar.invoice.InvoiceOuterClass.Invoice.class, com.prakhar.invoice.InvoiceOuterClass.Invoice.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 2;
    private float amount_;
    /**
     * <code>float amount = 2;</code>
     */
    public float getAmount() {
      return amount_;
    }

    public static final int CUSTOMERID_FIELD_NUMBER = 3;
    private volatile java.lang.Object customerId_;
    /**
     * <code>string customerId = 3;</code>
     */
    public java.lang.String getCustomerId() {
      java.lang.Object ref = customerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customerId_ = s;
        return s;
      }
    }
    /**
     * <code>string customerId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCustomerIdBytes() {
      java.lang.Object ref = customerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATE_FIELD_NUMBER = 4;
    private int state_;
    /**
     * <code>.State state = 4;</code>
     */
    public int getStateValue() {
      return state_;
    }
    /**
     * <code>.State state = 4;</code>
     */
    public com.prakhar.invoice.InvoiceOuterClass.State getState() {
      com.prakhar.invoice.InvoiceOuterClass.State result = com.prakhar.invoice.InvoiceOuterClass.State.valueOf(state_);
      return result == null ? com.prakhar.invoice.InvoiceOuterClass.State.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (amount_ != 0F) {
        output.writeFloat(2, amount_);
      }
      if (!getCustomerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, customerId_);
      }
      if (state_ != com.prakhar.invoice.InvoiceOuterClass.State.NEW.getNumber()) {
        output.writeEnum(4, state_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (amount_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, amount_);
      }
      if (!getCustomerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, customerId_);
      }
      if (state_ != com.prakhar.invoice.InvoiceOuterClass.State.NEW.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, state_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.prakhar.invoice.InvoiceOuterClass.Invoice)) {
        return super.equals(obj);
      }
      com.prakhar.invoice.InvoiceOuterClass.Invoice other = (com.prakhar.invoice.InvoiceOuterClass.Invoice) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && (
          java.lang.Float.floatToIntBits(getAmount())
          == java.lang.Float.floatToIntBits(
              other.getAmount()));
      result = result && getCustomerId()
          .equals(other.getCustomerId());
      result = result && state_ == other.state_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAmount());
      hash = (37 * hash) + CUSTOMERID_FIELD_NUMBER;
      hash = (53 * hash) + getCustomerId().hashCode();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.prakhar.invoice.InvoiceOuterClass.Invoice parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prakhar.invoice.InvoiceOuterClass.Invoice parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prakhar.invoice.InvoiceOuterClass.Invoice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prakhar.invoice.InvoiceOuterClass.Invoice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prakhar.invoice.InvoiceOuterClass.Invoice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prakhar.invoice.InvoiceOuterClass.Invoice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prakhar.invoice.InvoiceOuterClass.Invoice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.prakhar.invoice.InvoiceOuterClass.Invoice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.prakhar.invoice.InvoiceOuterClass.Invoice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.prakhar.invoice.InvoiceOuterClass.Invoice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.prakhar.invoice.InvoiceOuterClass.Invoice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.prakhar.invoice.InvoiceOuterClass.Invoice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.prakhar.invoice.InvoiceOuterClass.Invoice prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Invoice}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Invoice)
        com.prakhar.invoice.InvoiceOuterClass.InvoiceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.prakhar.invoice.InvoiceOuterClass.internal_static_Invoice_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.prakhar.invoice.InvoiceOuterClass.internal_static_Invoice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.prakhar.invoice.InvoiceOuterClass.Invoice.class, com.prakhar.invoice.InvoiceOuterClass.Invoice.Builder.class);
      }

      // Construct using com.prakhar.invoice.InvoiceOuterClass.Invoice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        amount_ = 0F;

        customerId_ = "";

        state_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.prakhar.invoice.InvoiceOuterClass.internal_static_Invoice_descriptor;
      }

      public com.prakhar.invoice.InvoiceOuterClass.Invoice getDefaultInstanceForType() {
        return com.prakhar.invoice.InvoiceOuterClass.Invoice.getDefaultInstance();
      }

      public com.prakhar.invoice.InvoiceOuterClass.Invoice build() {
        com.prakhar.invoice.InvoiceOuterClass.Invoice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.prakhar.invoice.InvoiceOuterClass.Invoice buildPartial() {
        com.prakhar.invoice.InvoiceOuterClass.Invoice result = new com.prakhar.invoice.InvoiceOuterClass.Invoice(this);
        result.id_ = id_;
        result.amount_ = amount_;
        result.customerId_ = customerId_;
        result.state_ = state_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.prakhar.invoice.InvoiceOuterClass.Invoice) {
          return mergeFrom((com.prakhar.invoice.InvoiceOuterClass.Invoice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.prakhar.invoice.InvoiceOuterClass.Invoice other) {
        if (other == com.prakhar.invoice.InvoiceOuterClass.Invoice.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getAmount() != 0F) {
          setAmount(other.getAmount());
        }
        if (!other.getCustomerId().isEmpty()) {
          customerId_ = other.customerId_;
          onChanged();
        }
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.prakhar.invoice.InvoiceOuterClass.Invoice parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.prakhar.invoice.InvoiceOuterClass.Invoice) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private float amount_ ;
      /**
       * <code>float amount = 2;</code>
       */
      public float getAmount() {
        return amount_;
      }
      /**
       * <code>float amount = 2;</code>
       */
      public Builder setAmount(float value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float amount = 2;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object customerId_ = "";
      /**
       * <code>string customerId = 3;</code>
       */
      public java.lang.String getCustomerId() {
        java.lang.Object ref = customerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          customerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string customerId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCustomerIdBytes() {
        java.lang.Object ref = customerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string customerId = 3;</code>
       */
      public Builder setCustomerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        customerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string customerId = 3;</code>
       */
      public Builder clearCustomerId() {
        
        customerId_ = getDefaultInstance().getCustomerId();
        onChanged();
        return this;
      }
      /**
       * <code>string customerId = 3;</code>
       */
      public Builder setCustomerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        customerId_ = value;
        onChanged();
        return this;
      }

      private int state_ = 0;
      /**
       * <code>.State state = 4;</code>
       */
      public int getStateValue() {
        return state_;
      }
      /**
       * <code>.State state = 4;</code>
       */
      public Builder setStateValue(int value) {
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.State state = 4;</code>
       */
      public com.prakhar.invoice.InvoiceOuterClass.State getState() {
        com.prakhar.invoice.InvoiceOuterClass.State result = com.prakhar.invoice.InvoiceOuterClass.State.valueOf(state_);
        return result == null ? com.prakhar.invoice.InvoiceOuterClass.State.UNRECOGNIZED : result;
      }
      /**
       * <code>.State state = 4;</code>
       */
      public Builder setState(com.prakhar.invoice.InvoiceOuterClass.State value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.State state = 4;</code>
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Invoice)
    }

    // @@protoc_insertion_point(class_scope:Invoice)
    private static final com.prakhar.invoice.InvoiceOuterClass.Invoice DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.prakhar.invoice.InvoiceOuterClass.Invoice();
    }

    public static com.prakhar.invoice.InvoiceOuterClass.Invoice getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Invoice>
        PARSER = new com.google.protobuf.AbstractParser<Invoice>() {
      public Invoice parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Invoice(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Invoice> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Invoice> getParserForType() {
      return PARSER;
    }

    public com.prakhar.invoice.InvoiceOuterClass.Invoice getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Invoice_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Invoice_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rinvoice.proto\"P\n\007Invoice\022\n\n\002id\030\001 \001(\t\022\016" +
      "\n\006amount\030\002 \001(\002\022\022\n\ncustomerId\030\003 \001(\t\022\025\n\005st" +
      "ate\030\004 \001(\0162\006.State*&\n\005State\022\007\n\003NEW\020\000\022\010\n\004P" +
      "AID\020\001\022\n\n\006FAILED\020\0022+\n\016InvoiceService\022\031\n\003P" +
      "ay\022\010.Invoice\032\010.InvoiceB\025\n\023com.prakhar.in" +
      "voiceb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Invoice_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Invoice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Invoice_descriptor,
        new java.lang.String[] { "Id", "Amount", "CustomerId", "State", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
